state_machine_rosparam_ws: /SimpleActionClientExample
success_switch:
   - type: state_reached
     state_name: "simple_action_client_example::State2"
failure_switch:
   - type: timeout
     duration: 10.0 # sec
