state_machine_rosparam_ws: /SmSimpleActionClient
success_switch:
   - type: state_reached
     state_name: "sm_simple_action_client::State2"
failure_switch:
   - type: timeout
     duration: 10.0 # sec
